"""
Builds docs/handover-report.md - a real handover document assembled from
what's actually been logged and written during the project, not invented.

Sections and where each one's data actually comes from:

  Time & tokens      - SQLite rollup of events.jsonl (real, if hooks have
                        been running)
  Pipeline status     - docs/review-log.md (real, if checkpoint-review has
                        been run) joined with agent_stats() run counts
  Decisions made      - scans every docs/*.md file for "Alternative
                        considered" / "Why rejected" blocks, a pattern this
                        kit's own agent prompts (research, mcp-provisioner,
                        cloud-engineer) are instructed to write. If an agent
                        didn't follow that pattern, its decisions won't show
                        up here - this is a scan, not an LLM summary.
  Achievements        - reviewed stages + passed runs, both from real data
  Flaws / open issues - HookBlock and held ReviewGate events, plus any
                        "Open questions" sections found in docs/*.md

Nothing here is generated by an LLM call. It's assembled from files already
on disk, which is the honest version of a "handover document" a local tool
can produce without inventing a narrative it can't back up.
"""
import datetime
import re
from pathlib import Path

from review_log import parse_review_log

DECISION_RE = re.compile(
    r"\*\*Alternative[s]? considered\*\*:?\s*(.+?)\n.*?\*\*Why rejected\*\*:?\s*(.+?)(?:\n\n|\n#|\Z)",
    re.IGNORECASE | re.DOTALL,
)
OPEN_Q_RE = re.compile(
    r"#{1,4}\s*Open question[s]?\s*\n+((?:[-*].+\n?)+)", re.IGNORECASE
)


def _fmt_duration(total_s):
    total_s = int(total_s)
    h, rem = divmod(total_s, 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h}h {m}m"
    if m:
        return f"{m}m {s}s"
    return f"{s}s"


def _fmt_tok(n):
    if n >= 1_000_000:
        return f"{n/1_000_000:.2f}M"
    if n >= 1_000:
        return f"{n/1_000:.1f}k"
    return str(int(n))


def _cost(tokens_in, tokens_out, cache_read, rates):
    model = rates.get("default_model", "claude-sonnet-4-5")
    rate = rates.get("models", {}).get(model, {"input": 3.0, "output": 15.0})
    cache_ratio = rates.get("cache_read_ratio", 0.1)
    cost = (
        tokens_in / 1e6 * rate["input"]
        + tokens_out / 1e6 * rate["output"]
        + cache_read / 1e6 * rate["input"] * cache_ratio
    )
    return cost, model, rate


def scan_decisions(docs_dir: Path):
    found = []
    if not docs_dir.exists():
        return found
    for md in sorted(docs_dir.glob("*.md")):
        text = md.read_text(encoding="utf-8", errors="replace")
        for m in DECISION_RE.finditer(text):
            alt = " ".join(m.group(1).split())[:200]
            why = " ".join(m.group(2).split())[:200]
            found.append({"source": md.name, "alternative": alt, "why_rejected": why})
    return found


def scan_open_questions(docs_dir: Path):
    found = []
    if not docs_dir.exists():
        return found
    for md in sorted(docs_dir.glob("*.md")):
        text = md.read_text(encoding="utf-8", errors="replace")
        for m in OPEN_Q_RE.finditer(text):
            lines = [l.strip("-* \t") for l in m.group(1).splitlines() if l.strip()]
            for l in lines:
                found.append({"source": md.name, "question": l[:220]})
    return found


def generate(project_root: Path, store, rates: dict, project_slug: str = ""):
    docs_dir = project_root / "docs"
    review_log = parse_review_log(docs_dir / "review-log.md")
    agent_stats = store.agent_stats() if store else []
    hook_blocks = store.hook_blocks(limit=200) if store else []
    held_gates = [g for g in (store.review_gate_events(limit=200) if store else []) if "held" in g["summary"].lower()]
    totals = store.token_totals() if store else {"input": 0, "output": 0, "cache_read": 0}
    total_tok = totals["input"] + totals["output"] + totals["cache_read"]
    cost, model, rate = _cost(totals["input"], totals["output"], totals["cache_read"], rates)
    total_work_s = sum(a["avg_duration_s"] * a["runs"] for a in agent_stats)
    total_runs = sum(a["runs"] for a in agent_stats)
    total_ok = sum(round(a["ok_pct"] / 100 * a["runs"]) for a in agent_stats)

    decisions = scan_decisions(docs_dir)
    open_qs = scan_open_questions(docs_dir)

    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = []
    lines.append(f"# Project Handover — {project_slug or project_root.name}")
    lines.append(f"Generated {now}")
    lines.append("")
    lines.append(
        "Assembled from `.claude/logs/events.jsonl`, `docs/review-log.md`, and the "
        "`Alternative considered` / `Open questions` sections of `docs/*.md`. Nothing "
        "below is LLM-generated narrative - it's a scan of what's actually on disk."
    )
    lines.append("")

    lines.append("## Time & tokens")
    lines.append(f"- Tracked work time (sum of logged subagent runs): **{_fmt_duration(total_work_s)}**")
    lines.append(f"- Subagent runs: **{total_runs}** ({total_ok} completed, {total_runs - total_ok} interrupted)")
    lines.append(f"- Total tokens: **{_fmt_tok(total_tok)}** (in {_fmt_tok(totals['input'])} / out {_fmt_tok(totals['output'])} / cache {_fmt_tok(totals['cache_read'])})")
    lines.append(f"- Estimated cost: **${cost:,.2f}** — assuming {model} at ${rate['input']}/${rate['output']} per Mtok (see config/rates.json; not a billing record)")
    lines.append("")

    lines.append("## Pipeline status")
    if review_log:
        lines.append("| Stage | Reviewed | Assessment |")
        lines.append("|---|---|---|")
        for e in review_log:
            assessment = " ".join(e["assessment"].split())[:140]
            lines.append(f"| {e['stage']} | {e['date'] or '—'} | {assessment} |")
    else:
        lines.append("No stages logged in docs/review-log.md yet.")
    lines.append("")

    lines.append("## Decisions made")
    if decisions:
        for d in decisions:
            lines.append(f"- **({d['source']})** considered *{d['alternative']}* — rejected: {d['why_rejected']}")
    else:
        lines.append("No `Alternative considered` / `Why rejected` blocks found in docs/*.md yet.")
    lines.append("")

    lines.append("## Achievements")
    if agent_stats:
        for a in sorted(agent_stats, key=lambda x: -x["runs"]):
            if a["runs"] == 0:
                continue
            lines.append(
                f"- **{a['name']}**: {a['runs']} run(s), {a['ok_pct']}% completed, "
                f"{_fmt_tok(a['total_tokens'])} tokens"
            )
    if not agent_stats or all(a["runs"] == 0 for a in agent_stats):
        lines.append("No completed subagent runs logged yet.")
    lines.append("")

    lines.append("## Flaws / open issues")
    if hook_blocks:
        lines.append(f"- {len(hook_blocks)} hook block(s) fired (guardrails denying a command) — most recent: *{hook_blocks[0]['summary']}*")
    if held_gates:
        lines.append(f"- {len(held_gates)} review-gate hold(s) — a subagent tried to start before its prerequisite stage was reviewed")
    if open_qs:
        for q in open_qs:
            lines.append(f"- **({q['source']})** open question: {q['question']}")
    if not hook_blocks and not held_gates and not open_qs:
        lines.append("No hook blocks, held gates, or recorded open questions.")
    lines.append("")

    lines.append("## Raw data")
    lines.append(f"- {store.event_count() if store else 0} events logged in `.claude/logs/events.jsonl`")
    lines.append("- Rollup database: `scripts/observability/rollup.db`")
    lines.append("- Full review history: `docs/review-log.md`")
    lines.append("")

    return "\n".join(lines)


def write_report(project_root: Path, store, rates: dict, project_slug: str = ""):
    md = generate(project_root, store, rates, project_slug)
    out_path = project_root / "docs" / "handover-report.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    return out_path, md
